checks:
  php: true
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
build:
  tests:
    override:
      -
        command: phpunit --coverage-clover=my-coverage-file
        coverage:
          file: my-coverage-file
          format: php-clover
